Pequeños ajustes para desarrollo

diff --git a/ensamble b/ensamble
--- a/ensamble
+++ b/ensamble
@@ -2,12 +2,16 @@
 
 
 if [[ $0 != "/usr/local/bin/ensamble" ]] ; then
-	echo "Error: you can't use ensamble script directly. Use through ensamble global command."
+	echo "Error: you can't use ensamble script directly. Must use it through ensamble global command."
 	exit 1
 fi
 
 echo "ensamble module."
 exit
+
+
+
+
 
 environment=${working_directory:="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"}
 
@@ -44,7 +48,7 @@ exit
 REPOSITORY_URL=${REPOSITORY_URL:=`readJson $environment/project.json Repository_URL`} || exit
 
 # (check if repository is reachable)
-`gitChecker $REPOSITORY_URL` || exit
+`gitChecker is_reachable $REPOSITORY_URL` || exit
 
 # (optional)
 PROJECT_NAME=`readJson $environment/project.json Name --optional`
